name: MLOps Quant Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.14
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.14"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create Directories
        run: mkdir -p data/raw models
      - name: Download Data
        run: python src/data_loader.py
      - name: Train Model
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          python src/train.py
      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest

  build-and-push:
    needs: test-code
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Don't push on Pull Requests, only merges.

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.14
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.14"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download Data & Train
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          python src/data_loader.py
          python src/train.py

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/quant-api:latest
